#methods



methods<-set_methods(methods_file = "E:/DwC/ExpedicionPacifico_2018/Metadatos/methods_file.md")
      

methods=list(
    sampling=list(studyExtent=list(description=list(para="El Distrito Nacional de Manejo Integrado (DNMI) Cabo Manglares, Bajo Mira y Frontera, se encuentra ubicado en el municipio de Tumaco, departamento de Nariño delimitado entre las latitudes 1°29'44” N y 1°40'04” N; y las longitudes 78°53'11 W y 79°09'40 W. En este distrito se ubica la desembocadura del río Mira y se caracteriza por ser un amplio sistema deltaico que abarca desde la bahía de Tumaco hasta la bahía de Ancón de Sardinas entre la frontera de Ecuador y Colombia.  
Los regímenes mareales de esta área se caracterizan por tener amplitudes que pueden llegar hasta los 4 metros (Polo, et al., 2008), esto hace que en el área se presenten amplio planos lodoso y extensas áreas intermareales donde se ubican bosques de manglar (e.g Rhizophora spp.) principalmente (Zambrano-Ortiz, et al., 2014). 
")),

        samplignDescription=list("Se realizaron muestreos en cada una de las estaciones en la fase diurna de la marea alta y la marea baja de los días 25 al 30 de noviembre de 2018. En cada estación se registró la transparencia del agua por medio de un disco Secchi, la temperatura y la salinidad por medio de un perfilador CTD 19 PLUS y se colectaron muestras de agua a nivel superficial para la realización de los análisis químicos con una botella Niskin de 5L, las cuales fueron preservadas y transportadas al laboratorio del Centro de Investigaciones Oceanográficas e Hidrográficas del Pacífico – CCCP para posteriormente ser procesadas y analizadas. 
Las muestras de plancton se colectaron con redes de arrastre utilizando una red cónica de 30 cm de diámetro y de 53 µm de poro de malla para el fitoplancton y una red tipo bongo de 50 cm de diámetro con 300 y 500 µm de poro de malla para el zooplancton; cada una de las redes contaba con un flujómetro mecánico marca General Oceanic® para los posteriores cálculos de volumen de agua filtrado. Se realizaron arrastres superficiales de 5 minutos aproximadamente a una velocidad de dos nudos desde un bote tipo Zodiac®, luego de esto se preservó 1 litro de cada tipo de muestra de plancton, con formol buferizado al 4% y se transportaron al laboratorio para su posterior análisis."
)),
    qualityControl=list(description=
        " El control de calidad de la toma de muestras se garantizó a través del seguimiento de los protocolos del Sistema de Gestión de Calidad del Laboratorio de la Dirección General Marítima (SGL-DIMAR). Para la toma de muestras se siguió el procedimiento \"M5-00-PRO-027- versión 2: Toma de Muestras\" el cuál está basado en el Standard Methods for the Examination of Water & Wastewater: Plankton (Rice et al 2017).En los ensayos de laboratorio se utilizó el procedimiento \"M5-00-PRO-094 versión 0: Determinación de la Densidad del Fitoplancton\" del SGL-DIMAR para la determinación semicuantitativa de la densidad del fitoplancton, el cuál esta basado en los métodos analíticos de Villafañe et al. (995). Todos los conteos primarios se registraron en el formato de conteo primarios \"M5-00-FOR-136 verión 1: Datos primarios para el análisis de densidad de plancton y macroinvertebrados bentónicos\" del cuál se crearon las matrices de densidad utilizando las formulas del método de análisis semicuantitativos del conteo por campos. Para la verificación de la taxonomía se utilizó el paquete de R \"worrms\" (Chamberlain y Vanhoorne 2023) usando el comando taxamatch, el cual  verifica los nombres de las especies con la información del Registro Mundial de Especies Marinas – WoRMS (WoRMS Editorial Board, 2019), sugiriendo correcciones y la jerarquía taxonómica de cada taxón.Por último, se ensamblaron los datos en el estandar Darwin Core utilizando el paquete para manejo de datos de R \"dplyr\" (Wickham  et al. 2023) y de que cumpliera con los estándares del Darwin Core, utilizando la herramienta de validacción de datos del GBIF."
      ),
    methodStep=list(
                list(description=list(para="Se realizaron muestreos en cada una de las estaciones en la fase diurna de la marea alta y la marea baja de los días 25 al 30 de noviembre de 2018. En cada estación se registró la transparencia del agua por medio de un disco Secchi, la temperatura y la salinidad por medio de un perfilador CTD 19 PLUS y se colectaron muestras de agua a nivel superficial para la realización de los análisis químicos con una botella Niskin de 5L, las cuales fueron preservadas y transportadas al laboratorio del Centro de Investigaciones Oceanográficas e Hidrográficas del Pacífico – CCCP para posteriormente ser procesadas y analizadas. ")),
                list(description=list(para="Las muestras de plancton se colectaron con redes de arrastre utilizando una red cónica de 30 cm de diámetro y de 53 µm de poro de malla para el fitoplancton y una red tipo bongo de 50 cm de diámetro con 300 y 500 µm de poro de malla para el zooplancton; cada una de las redes contaba con un flujómetro mecánico marca General Oceanic® para los posteriores cálculos de volumen de agua filtrado. Se realizaron arrastres superficiales de 5 minutos aproximadamente a una velocidad de dos nudos desde un bote tipo Zodiac®, luego de esto se preservó 1 litro de cada tipo de muestra de plancton, con formol buferizado al 4% y se transportaron al laboratorio para su posterior análisis.")),
                list(description=list(para="De las muestras de agua colectadas se realizaron análisis químicos para determinar el pH, las concentraciones de solidos suspendidos y nutrientes como el amonio, nitritos, nitratos, fosfatos y silicatos. La determinación del amonio se realizó siguiendo el método colorimétrico del azul de indofenol descrito por Strickland y Parsons (1972) para nitritos se aplicó el método colorimétrico descrito por Bendschneider y Robinson (1952), para los nitratos el método colorimétrico de reducción con cadmio-cobre publicado por Strickland y Parsons (1972), para fosfatos el método del  ácido ascórbico de Murphy & Riley (1958) y para silicatos el método del metol-sulfito descrito por Strickland & Parson (1972).")),
                list(description=list(para="De las muestras biológicas colectadas se determinó el número de géneros y abundancia de células de fitoplancton por litro por medio de la toma de alícuotas y el posterior conteo en una cámara Sedgwick-Rafter de 1 ml de volumen. Junto a esto se determinó la concentración de clorofila –a utilizando el método tricromático 10200 H descrito en el Standard Methods for the Examination of Water and Wasterwater (American Public Health Association (APHA), 2005). De las muestras de zooplancton se extrajeron todos los estadios de las larvas de peces y se calculó su abundancia. Posterior a esto, de la muestra restante de zooplancton se separaron alícuotas de ½ (500 ml) por medio de un fraccionador Folsom. Una de las alícuotas fue destinada para el cálculo de la productividad secundaria de la comunidad zooplanctónica, exceptuando las larvas de peces. La otra alícuota fue preservadas para posteriores análisis de la comunidad zooplanctónica que serán tratados en otras publicaciones."))
                    
    )
)


