

Eventos_encabezados<-list("parentEventID","eventID",  
"samplingProtocol","sampleSizeValue",
 "sampleSizeUnit","samplingEffort",
 "eventDate", "startDayOfYear",
"endDayOfYear", "year",
"month","day", 
"verbatimEventDate","eventTime",
"habitat",   "fieldNumber",  
"fieldNotes","eventRemarks", 
"type", "institutionCode",
"institutionID", "datasetName",  
"datasetID", "modified", 
"language",  "license",  
"rightsHolder",  "accessRights", 
"bibliographicCitation",    "references",   
"ownerInstitutionCode",     "informationWithheld",     
"dataGeneralizations",      "dynamicProperties",       
"locationID","higherGeography",
"higherGeographyID","continent",
"waterBody", "islandGroup",  
"island",    "country",  
"countryCode",   "stateProvince",
"county",    "municipality", 
"locality",  "verbatimLocality",
"verbatimElevation","minimumElevationInMeters",
"maximumElevationInMeters", "verticalDatum",
"verbatimDepth", "minimumDepthInMeters",    
"maximumDepthInMeters",     "minimumDistanceAboveSurfaceInMeters",
"maximumDistanceAboveSurfaceInMeters", "locationAccordingTo",     
"locationRemarks","verbatimLatitude",
"verbatimLongitude","verbatimCoordinates",     
"verbatimCoordinateSystem", "verbatimSRS",  
"decimalLatitude","decimalLongitude",
"geodeticDatum", "coordinateUncertaintyInMeters",      
"coordinatePrecision",      "pointRadiusSpatialFit",   
"footprintWKT",  "footprintSRS", 
"footprintSpatialFit",      "georeferencedBy",
"georeferencedDate","georeferenceProtocol",    
"georeferenceSources",    "georeferenceVerificationStatus",     
"georeferenceRemarks",      "geologicalContextIDs",    
"earliestEonOrLowestEonothem","latestEonOrHighestEonothem",
"earliestEraOrLowestErathem", "latestEraOrHighestErathem", 
"earliestPeriodOrLowestSystem","latestPeriodOrHighestSystem",
"earliestEpochOrLowestSeries","latestEpochOrHighestSeries",
"earliestAgeOrLowestStage", "latestAgeOrHighestStage", 
"lowestBiostratigraphicZone", "highestBiostratigraphicZone",
"lithostratigraphicTerms",  "group",    
"formation", "member",   
"bed"   )
