

Eventos_encabezados<-list(
parentEventID="Un identificador único para la categoría superior del evento de muestreo. Por ejemplo, el identificador del muestreo de un cuadrante, parcela o transecto independientemente del tiempo o temporada cuando se realice el muestro. \nEste identificador es más general que el eventID y puede agrupar varios eventID. Este elemento debe estar acompañado siempre del elemento eventID.",
eventID="Un identificador único para el Evento de muestreo, que ocurre en un lugar y tiempo determinado. Por ejemplo, el identificador del muestreo de un cuadrante, parcela o transecto en un tiempo o temporada específicos. Este identificador es más específico que el parentEventID.Este elemento puede estar acompañado del elemento parentEventID",  
samplingProtocol="El nombre, la descripción o la referencia del método o protocolo de muestreo usado para realizar el muestreo. Se recomienda acompañar este elemento con el elemento samplingEffort.",
sampleSizeValue="Un valor numérico para una medición del tamaño (duración de tiempo, longitud, área o volumen) de una muestra en un evento de muestreo. Documentar este elemento junto con el elemento sampleSizeUnit. Se recomienda hacer uso del Sistema Internacional de Unidades (SI).",
sampleSizeUnit="La unidad de medida de la magnitud (tiempo de duración, longitud, área o volumen) de una muestra en un evento de muestreo. Documentar este elemento junto con el elemento sampleSizeValue.",
samplingEffort="El esfuerzo de muestreo en tiempo y/o espacio realizado durante el evento de muestreo. Documentar este elemento junto con el elemento samplingProtocol.",
eventDate="La fecha o el intervalo durante el cual se produjo el evento de observación o colecta de un organismo o muestra. No es adecuado para una fecha en un contexto geológico. Debe estar documentada en el esquema de codificación ISO 8601 (AAAA-MM-DD o para un intervalo de fechas: AAAA-MM-DD/AAAA-MM-DD).", 
startDayOfYear="Día inicial del evento, contando a partir del primer día del año del evento y documentado en formato de números ordinales (siendo 1 el primero de enero y 365 el 31 de diciembre en año no bisiesto).",
"endDayOfYear",
"year",
"month",
"day", 
"verbatimEventDate",
"eventTime",
"habitat",   
"fieldNumber",  
"fieldNotes",
"eventRemarks", 
"type", 
"institutionCode",
"institutionID",
"datasetName",  
"datasetID", 
"modified", 
"language", 
"license",  
"rightsHolder",
"accessRights", 
"bibliographicCitation",
"references",   
"ownerInstitutionCode",
"informationWithheld",     
"dataGeneralizations",
"dynamicProperties",       
"locationID",
"higherGeography",
"higherGeographyID",
"continent",
"waterBody",
"islandGroup",  
"island",
"country",  
"countryCode",
"stateProvince",
"county",
"municipality", 
"locality",
"verbatimLocality",
"verbatimElevation",
"minimumElevationInMeters",
"maximumElevationInMeters",
"verticalDatum",
"verbatimDepth",
"minimumDepthInMeters",    
"maximumDepthInMeters",
"minimumDistanceAboveSurfaceInMeters",
"maximumDistanceAboveSurfaceInMeters",
"locationAccordingTo",     
"locationRemarks",
"verbatimLatitude",
"verbatimLongitude",
"verbatimCoordinates",     
"verbatimCoordinateSystem",
"verbatimSRS",  
"decimalLatitude",
"decimalLongitude",
"geodeticDatum",
"coordinateUncertaintyInMeters",      
"coordinatePrecision",
"pointRadiusSpatialFit",   
"footprintWKT",
"footprintSRS", 
"footprintSpatialFit",
"georeferencedBy",
"georeferencedDate",
"georeferenceProtocol",    
"georeferenceSources",
"georeferenceVerificationStatus",     
"georeferenceRemarks",
"geologicalContextIDs",    
"earliestEonOrLowestEonothem",
"latestEonOrHighestEonothem",
"earliestEraOrLowestErathem",
"latestEraOrHighestErathem", 
"earliestPeriodOrLowestSystem",
"latestPeriodOrHighestSystem",
"earliestEpochOrLowestSeries","latestEpochOrHighestSeries",
"earliestAgeOrLowestStage", "latestAgeOrHighestStage", 
"lowestBiostratigraphicZone", "highestBiostratigraphicZone",
"lithostratigraphicTerms",  "group",    
"formation", "member",   
"bed"  )

occurrence_Encabezados<-list(
 "occurrenceID",                       "basisOfRecord",                     
 "type",                               "institutionCode",                   
 "institutionID",                      "collectionCode",                    
 "collectionID",                       "catalogNumber",                     
 "datasetName",                        "datasetID",                         
 "modified",                           "language",                          
 "license",                            "rightsHolder",                      
 "accessRights",                       "bibliographicCitation",             
 "references",                         "ownerInstitutionCode",              
 "informationWithheld",                "dataGeneralizations",               
 "dynamicProperties",                  "recordNumber",                      
 "recordedBy",                         "recordedByID",                      
 "organismID",                         "individualCount",                   
 "organismQuantity",                   "organismQuantityType",              
 "organismName",                       "organismScope",                     
 "associatedOrganisms",                "previousIdentifications",           
 "organismRemarks",                    "sex",                               
 "lifeStage",                          "reproductiveCondition",             
 "behavior",                           "establishmentMeans",                
 "degreeOfEstablishment",              "pathway",                           
 "occurrenceStatus",                   "preparations",                      
 "disposition",                        "otherCatalogNumbers",               
 "associatedMedia",                    "associatedOccurrences",             
 "associatedReferences",               "associatedSequences",               
 "associatedTaxa",                     "occurrenceRemarks",                 
 "materialSampleID",                   "parentEventID",                     
 "eventID",                            "samplingProtocol",                  
 "sampleSizeValue",                    "sampleSizeUnit",                    
 "samplingEffort",                     "eventDate",                         
 "startDayOfYear",                     "endDayOfYear",                      
 "year",                               "month",                             
 "day",                                "verbatimEventDate",                 
 "eventTime",                          "habitat",                           
 "fieldNumber",                        "fieldNotes",                        
 "eventRemarks",                       "locationID",                        
 "higherGeography",                    "higherGeographyID",                 
 "continent",                          "waterBody",                         
 "islandGroup",                        "island",                            
 "country",                            "countryCode",                       
 "stateProvince",                      "county",                            
 "municipality",                       "locality",                          
 "verbatimLocality",                   "verbatimElevation",                 
 "minimumElevationInMeters",           "maximumElevationInMeters",          
 "verticalDatum",                      "verbatimDepth",                     
 "minimumDepthInMeters",               "maximumDepthInMeters",              
 "minimumDistanceAboveSurfaceInMeters","maximumDistanceAboveSurfaceInMeters",
 "locationAccordingTo",                "locationRemarks",                   
 "verbatimLatitude",                   "verbatimLongitude",                 
 "verbatimCoordinates",                "verbatimCoordinateSystem",          
 "verbatimSRS",                        "decimalLatitude",                   
 "decimalLongitude",                   "geodeticDatum",                     
 "coordinateUncertaintyInMeters",      "coordinatePrecision",               
 "pointRadiusSpatialFit",              "footprintWKT",                      
 "footprintSRS",                       "footprintSpatialFit",               
 "georeferencedBy",                    "georeferencedDate",                 
 "georeferenceProtocol",               "georeferenceSources",               
 "georeferenceVerificationStatus",     "georeferenceRemarks",               
 "geologicalContextID",                "earliestEonOrLowestEonothem",       
 "latestEonOrHighestEonothem",         "earliestEraOrLowestErathem",        
 "latestEraOrHighestErathem",          "earliestPeriodOrLowestSystem",      
 "latestPeriodOrHighestSystem",        "earliestEpochOrLowestSeries",       
 "latestEpochOrHighestSeries",         "earliestAgeOrLowestStage",          
 "latestAgeOrHighestStage",            "lowestBiostratigraphicZone",        
 "highestBiostratigraphicZone",        "lithostratigraphicTerms",           
 "group",                              "formation",                         
 "member",                             "bed",                               
 "identificationID",                   "identifiedBy",                      
 "identifiedByID",                     "dateIdentified",                    
 "identificationReferences",           "identificationVerificationStatus",  
 "typeStatus",                         "verbatimIdentification",            
 "identificationRemarks",              "identificationQualifier",           
 "scientificName",                     "scientificNameAuthorship",          
 "taxonID",                            "scientificNameID",                  
 "higherClassification",               "kingdom",                           
 "phylum",                             "class",                             
 "order",                              "family",                            
 "subfamily",                          "genus",                             
 "genericName",                        "subgenus",                          
 "infragenericEpithet",                "specificEpithet",                   
 "infraspecificEpithet",               "cultivarEpithet",                   
 "taxonRank",                          "verbatimTaxonRank",                 
 "vernacularName",                     "taxonomicStatus",                   
 "acceptedNameUsage",                  "acceptedNameUsageID",               
 "parentNameUsage",                    "parentNameUsageID",                 
 "originalNameUsage",                  "originalNameUsageID",               
 "nameAccordingTo",                    "nameAccordingToID",                 
 "namePublishedIn",                    "namePublishedInID",                 
 "namePublishedInYear",                "taxonConceptID",                    
 "nomenclaturalCode",                  "nomenclaturalStatus",               
 "taxonRemarks")                 
